### ISSUE TITLE
[Documentation] Point links to configuration tools to the production URLs instead of source

### ISSUE THREAD

**Issue by malekai101** [hashicorp/hcdiag-ext#21]
The links in the README.md for the Terraform and Vault configuration generators point to the code files in source control instead of the hosted applications.  End users using the README as documentation could not click on the links to generate the configuration files.  

This occurs in the `New for v0.6.x` section and the `Install and run hcdiag-ext configuration on your local machine or a product instance` sections.  

Terraform points here: https://github.com/hashicorp/hcdiag-ext/blob/main/terraform-ent-configuration.html
It should point here: https://hashicorp.github.io/hcdiag-ext/terraform-ent-configuration.html

Vault points here: https://github.com/hashicorp/hcdiag-ext/blob/main/vault-ent-configuration.html
It should point here: https://hashicorp.github.io/hcdiag-ext/vault-ent-configuration.html

**Comment by malekai101** [comment]
I created a fork and opened pull request 22 for this.

**Comment by roooms** [comment]
Thanks! Use of hcdiag-ext is minimal now, but I have merged this as it improves the user experience for those who are using it.
